### ISSUE TITLE
How to integrate my nodejs backend with apxor. 

### ISSUE THREAD

**Issue by vk-98** [apxor/docs#2]
I am looking to integrate Apxor with my node js application, but I cannot understand where I can get the site id for my application. And steps should I follow. 

Can you please provide some snippets explaining the same?

**Comment by vk-98** [comment]
One more thing that I want to ask is, Can we integrate the APXOR with the backend?

**Comment by arajajyothibabu** [comment]
Hi @vk-98 , please [contact](https://www.apxor.com/contact-us) Apxor for further information on integration.

**Comment by arajajyothibabu** [comment]
> One more thing that I want to ask is, Can we integrate the APXOR with the backend?

Apxor JS SDK is for the client-side, but you can log your custom events in the backend like NodeJs.
